apiVersion: v1
kind: Service
metadata:
  name: flaskapp
  namespace: 3-tiers-app 
  labels:
    app: flaskapp
spec:
  ports:
  - port: 5090
    targetPort: 5090
    protocol: TCP
  selector:
    appengine: flaskapp