apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: 3-tiers-app 
  labels:
    webengine: nginx
spec:
  selector:    
    webengine: nginx
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30036
    protocol: TCP